### ISSUE TITLE
Update RootHandler so that it handles TTrees 

### ISSUE THREAD

**Issue by spaulaus** [spaulaus/paass-lc#137]
## Expected Behavior

RootHandler should handle Trees for us as well as histograms. This prevents users from needing specialized root files and writing that may overlap with the "official one"
## Current Behavior

The guts for TTrees exists, but isn't used. 
## Context

We have having an issue in @jjvz's [code](https://github.com/jjvz/paass-laughing-conqueror/tree/feature-pr270) where we're unable to view the online histograms due to the tree constantly writing out of sync with the histogramming. 
## Acceptance Criteria

- [x] Experiment processors no longer need to define their own ROOT files to plot TTrees
- [x] TTrees and Branches are handled via RootHandler
- [x] Update `TwoChanTimingProcessor` to provide users concrete example
- [x] Update `TemplateExpProcessor` to provide users concrete example

**Comment by jjvz** [comment]
(1) I was wanting to suggest you provide some "standard" templates as examples for users, such as TemplateExpProcessor.  I used your initial Pr270Processor in your pr270 branch as template for my adapted version.  Good place to start.
(2) Users should still have option to change their ROOT TTree, e.g. rename the tree, add branches etc. as I'm doing in the experiment processor.

**Comment by spaulaus** [comment]
The name of the tree will be defined by the user, ditto for branches. RootHandler will only keep track of that information and ensure that duplicates are not entered.

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#137

**Comment by spaulaus** [comment]
This turns out to be much more complicated than initially thought. You can find the full details in this thread : https://root-forum.cern.ch/t/disable-ttree-autosave-when-calling-ttree-fill-to-write-tree-in-parallel/28337

**Comment by spaulaus** [comment]
I'm going to investigate a workaround here. If we define two TFiles one for histograms and one for trees, we may be able to circumvent this issue.
