### ISSUE TITLE
GSL and GSL-devel needed as prerequisites for installation of PAASS-LC

### ISSUE THREAD

**Issue by jjvz** [spaulaus/paass-lc#157]
User needs to "yum install gsl-devel" and "yum install gsl" (on CentOS7) as prerequisites for paass-lc installation.

## Current Behavior
ccmake complains if the GSL is out of date 

## Possible Solution (optional)
Update GSL:
yum install gsl-devel
yum install gsl

**Comment by spaulaus** [comment]
Install instructions are updated: https://github.com/spaulaus/paass-lc/wiki/Installation#required-packages
