### ISSUE TITLE
Regex error when running poll2

### ISSUE THREAD

**Issue by spaulaus** [spaulaus/paass-lc#232]
## Expected Behavior

The program doesn't crash with a regex exception.
## Current Behavior

The software crashes with a regex exception.
## Context

Encountered while trying to setup the software on a new system. 
## Possible Solution (optional)

Don't know what the problem is yet. 
## Acceptance Criteria

- [ ] Users no longer have a regex error when attempting to load the software.

### Your Environment

| Component | Value  |
|--|--|
|Operating system | Ubuntu 14.04 LTS |
|Kernel Version   | 3.13.0-160-generic |
|CMake Version    | 3.2.2 |
|GCC Version      | 5.5 |
|ROOT Version     | 5.34/14 |
|GSL Version      | 1.16 |

### Steps to Reproduce

1. 
2.

### Screenshots

![image](https://user-images.githubusercontent.com/1553042/47254362-7b2e8d80-d42f-11e8-88a4-448210784156.png)
![image](https://user-images.githubusercontent.com/1553042/47254365-808bd800-d42f-11e8-8629-fc08d6757346.png)

### Other Assets
[Configuration File](https://gist.github.com/spaulaus/f9f9981cdd8b104fe0a6f17961a5918f)

**Comment by spaulaus** [comment]
Found another error. The module base directory was missing its leading `/`.

**Comment by spaulaus** [comment]
@jjvz : Is it the same error using the same configuration file, or a different one?

**Comment by jjvz** [comment]
This is the result of 'ctest' in the "/root/paass-lc/build" directory:
![image](https://user-images.githubusercontent.com/18749257/47488163-1797cc00-d844-11e8-9ef2-3bf22789daef.png)

**Comment by jjvz** [comment]
I use the following pixie-cfg.xml config file which I correct from the created one during make, and copy to the directory from where I run poll2, i.e. /home/pr270user/Software/paass_usr/acq
![image](https://user-images.githubusercontent.com/18749257/47488429-a6a4e400-d844-11e8-8ed3-ee63e330a7a8.png)

**Comment by jjvz** [comment]
This is the output from running poll2:
![image](https://user-images.githubusercontent.com/18749257/47488529-dc49cd00-d844-11e8-8f62-3d2b40104d95.png)

**Comment by spaulaus** [comment]
The results of `ctest` on @jjvz 's setup implies that the compiler, while compiling the files properly, cannot run the regex? 
![image](https://user-images.githubusercontent.com/1553042/47494962-fb366800-d820-11e8-9845-96cd30714058.png)

**Comment by spaulaus** [comment]
@jjvz : The two failing tests are most likely also due to regex errors. Can you confirm you compiler version, please?

**Comment by spaulaus** [comment]
Found to be an issue with GCC version. Gcc 4.8 has incomplete regex support. It compiles without issue, but cannot run the expressions properly.
