### ISSUE TITLE
custom experiment processor not executing

### ISSUE THREAD

**Issue by ljlabs** [spaulaus/paass-lc#246]
## Expected Behavior
I am in the process of writing a custom experiment processor. The class is initialized and the process method should be executed.

## Current Behavior
At this point my processor is initialized however the process method is not being executed. I have noticed this is happening for other experiment processors as well.

## Context
I am trying to create an experiment processor to extract time and energy data from each channel to an external csv file. I have managed to extract this data using the DetectorDriver's ProcessEvent method however i would much prefer to make this an experiment processor.

I have found that my processor is initialized however its process method is never called

## Acceptance Criteria
the execution of my experiment processor's process method

### Your Environment
|Operating system | Ubuntu 18.04.1 LTS |
|Kernel Version   | 4.15.0-47-generic |
|CMake Version    | cmake version 3.10.2 |
|GCC Version      | gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0 |
|ROOT Version     | 6.16/00 |
|GSL Version      | 2.4 |

**Comment by spaulaus** [comment]
@ljlabs : Sorry for the late reply. What release are you using? Here's a list of things that I recommend you check : 

1. Ensure that you define your class properly in `DetectorDriverXmlParser::ParseProcessors`.
2. Ensure that you've associated your Processor with a detector type. See Lines [63](https://github.com/spaulaus/paass-lc/blob/master/Analysis/Utkscan/experiment/source/IS600Processor.cpp#L63) to [66](https://github.com/spaulaus/paass-lc/blob/master/Analysis/Utkscan/experiment/source/IS600Processor.cpp#L66) in [IS600Processor.cpp](https://github.com/spaulaus/paass-lc/blob/master/Analysis/Utkscan/experiment/source/IS600Processor.cpp).

**Comment by ljlabs** [comment]
It appears as the firmware that my XIA system is using is not supported by the paass-lc framework

I have tried to create a new firmware type in paass-lc. this may be the issue. I Will get back to you soon but this seems like it may be causing this issue

**Comment by spaulaus** [comment]
What firmware version do you have? Are you using a Pixie16 system?

**Comment by spaulaus** [comment]
As a follow-up, I don't think the firmware is an issue. You said that you can get the data from DetectorDriver directly, which indicates the data unpacked correctly.

**Comment by ljlabs** [comment]
The firmware version it uses is version 34703. when i try to use the exsiting known firmware versions it fails saying the version is too new.

**Comment by spaulaus** [comment]
@ijlabs : That is just a warning message. The last firmware used in the data mask was 34688. 

Again if you were able to obtain the information from DetectorDriver then the problem lies with your experiment processor. I suspect that option two from my first post is your issue.

**Comment by ljlabs** [comment]
Thank You option 2 was the issue.
