### ISSUE TITLE
TwoChanTimingProcessor Generates empty histograms

### ISSUE THREAD

**Issue by ljlabs** [spaulaus/paass-lc#250]
Calling the two chan timing processor by altering the channels in the example config file found at
Analysis/Utkscan/share/utkscan/cfgs/examples/example.xml
Generates empty histograms except for the Error codes plot which appears to be every event coming from the detectors.
## Expected Behavior
It is expected that not all data be plotted in the "Error Codes" histogram and some data be plotted in 

 "Amplitude Distribution - Start"
 "Amplitude Distribution - Stop"
 "Random Sample of Start Traces"
 "Random Sample of Stop Traces"

## Current Behavior
All data gets plotted in  the "Error Codes" histogram
and no data is found in

 "Amplitude Distribution - Start"
 "Amplitude Distribution - Stop"
 "Random Sample of Start Traces"
 "Random Sample of Stop Traces"

## Context
I Am trying to use the HighResTimingData for the purposes of finding coincidece events between 2 detectors however all time data coming from the HighResTimingData(*(*it)).GetHighResTimeInNs(). object is set to 0ns

### Your Environment
|Operating system |  Ubuntu 18.04.1 LTS  |
|Kernel Version   | 4.15.0-51-generic |
|CMake Version    | 3.10.2 |
|GCC Version      | gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0 |
|ROOT Version     | 6.16/00 |
|GSL Version      | 2.4 |

### Steps to Reproduce

1. 
2.

**Comment by spaulaus** [comment]
@ljlabs : Do you have trace capture enabled on the hardware? You need to have traces in order to do high resolution timing calculations. You'll also need to ensure that you have the proper parameters set for the fit.

**Comment by ljlabs** [comment]
The parameters are optimized.

Is trace capture enabled by default during list mode acquisition or does it need to be enabled separately

**Comment by spaulaus** [comment]
Yes. You need to enable the traces from the channel csra.

**Comment by ljlabs** [comment]
Yes it is enabled

**Comment by spaulaus** [comment]
Then my next suggestion would be to ensure that you have setup the configuration file properly. You will need to enable the WaveformAnalyzer in the DetectorDriver mode. Also, add the Trace node to channels with traces. You can find information on how to do this on the wiki: https://github.com/spaulaus/paass-lc/wiki/Utkscan-Configuration

**Comment by ljlabs** [comment]
I am using the example config file found at 
`https://github.com/spaulaus/paass-lc/blob/9843ebe97506eaf66e76cba84b3dde668c1b8806/Analysis/Utkscan/share/utkscan/cfgs/examples/example.xml`
The only things i changed is the channel numbers, removed module 1 & 2, and changed the firmware number

**Comment by spaulaus** [comment]
Did you confirm that the Trace delay and other parameters are appropriate for your signal? You can view the signals using Scope, and check the performance of the parameters

**Comment by kapoorkush** [comment]
> Yes. You need to enable the traces from the channel csra.

Does that means csra value to be: 2^(2)+2^(14)+2^(8)= 16644, enabling Good Channel, Trace Capture & gain factor (x4)?

**Comment by spaulaus** [comment]
Yes, you need to ensure that you have bits 2 (Good Channel) and 8 (Enable Trace Capture) of the CHANNEL_CSRA enabled. See Table 3-2 in the [Pixie-16 User's Manual](https://www.xia.com/wp-content/uploads/2018/04/Pixie16_UserManual.pdf).

**Comment by spaulaus** [comment]
The issue was with setting the CSRA. Closing issue as resolved
