### ISSUE TITLE
PR270 - iThemba LABS

### ISSUE THREAD

**Issue by spaulaus** [spaulaus/paass-lc#69]
# Introduction
This will serve as a software development log for the PR270 experiment at iThemba LABS. This code is tracked in this [branch](/spaulaus/paass-laughing-conqueror/tree/pr270). 

# Assumptions
1. The Polarization signals occur when the beam polarization is swapped from Up to Down or Down to Up. I.e. I get a Up logic signal when the beam is switched to up polarizaiton. I get a down polarization signal when the beam is switched to down polarization. 
![image](https://user-images.githubusercontent.com/1553042/34945232-97fc293e-f9d0-11e7-969d-23be6a7e9bfb.png)
2. That the logic signals will be split. This facilitates triggering on both the rising and falling edge of the signal. It provides additional redundancy when recording TTL signals.
3. There will be a pulser signal in the setup to monitor deadtime. 
4. We will want to gate the telescopes on beam up or beam down.

**Comment by jjvz** [comment]
The beam polarization timing is more like the picture here, i.e. the polarization is "up" for about 10 sec. wherein a logic "on" signal comes from the "pol-up" output of the ion source. During this time the signal from "pol-down" output of the ion source is "off". After this 10s period the polarization conditions are switched, pol-down is now "on" and pol-up is "off". 
![beam-up-down-logic](https://user-images.githubusercontent.com/18749257/36494337-706b4832-173a-11e8-93e9-9a3135844eeb.png)

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#69

**Comment by spaulaus** [comment]
Experiment finished successfully.
