### ISSUE TITLE
Move to using ExternalProject within CMake

### ISSUE THREAD

**Issue by ksmith0** [spaulaus/paass-lc#7]
I suggest we move to using the ExternalProject scheme of CMake for all submodues. This will permit each submodule to have independent CMake projects and remove possible collisions.

Lets take an example situation where you have this setup:
```
project/
|- CMakeLists.txt
|- external/
   |- CMakeLists.txt
   |- subproject/
```

There are two ways to do this using git to manage submodules or permitting CMake to handle them. In the latter the `subproject` directory above would not be present. The main `CMakeLists.txt` would simply read
```cmake
add_subdirectory(external)
```
The `external\CMakeLists.txt` file would contain
```cmake
include(ExternalProject)

ExternalProject_Add(subproject
   PREFIX subproject

   #This project can be fetched directly from the git repo
   #GIT_REPOSITORY https://github.com/spaualus/subproject

   #OR if already packaged with submodule we can indicate the location of the source.
   SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/subproject

   CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
)
```

The above file has selected the former case where the submodule is part of the project as managed by git. To use the latter case the `GIT_REPOSITORY` line would be uncommented and the `SOURCE_DIR` line removed. If we want to further restrict where the subproject is being pulled from we could use the `GIT_TAG` and identify a specific branch, tag, or commit. The submodule would then be cloned by CMake inside the build directory.

More details on CMake's ExternalProject at https://cmake.org/cmake/help/v3.8/module/ExternalProject.html

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#7

**Comment by spaulaus** [comment]
I'm moving this to won't fix. Many of our 3rd party dependencies are standard packages now.
